'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  ClipboardList, Search, ArrowRight,
  Clock, CheckCircle2, XCircle, AlertTriangle, FileText
} from 'lucide-react';
import { cn, formatEquipmentType, priorityBg, statusBg, formatStatus, formatDate, timeAgo } from '@/lib/utils';

export default function WorkOrdersListPage() {
  const [workOrders, setWorkOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/work-orders')
      .then(res => res.json())
      .then(res => {
        if (res.success) setWorkOrders(res.data);
        setLoading(false);
      })
      .catch(console.error);
  }, []);

  if (loading) {
    return <div className="animate-pulse p-4">Loading work orders...</div>;
  }

  const draftCount = workOrders.filter(w => w.status === 'DRAFT').length;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-end gap-4">
        <div>
          <div className="text-sm font-semibold tracking-wider text-orange-600 mb-1 uppercase">Maintenance Execution</div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Work Orders</h1>
          <p className="text-slate-500 mt-1 max-w-2xl">Review, approve, and track maintenance work orders generated by AI triage or technicians.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-1">Total</p>
            <h3 className="text-2xl font-bold text-slate-900">{workOrders.length}</h3>
          </div>
          <div className="p-2 bg-slate-100 text-slate-600 rounded-lg"><ClipboardList className="w-5 h-5" /></div>
        </div>
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-1">Needs Review</p>
            <h3 className="text-2xl font-bold text-slate-900">{draftCount}</h3>
          </div>
          <div className="p-2 bg-blue-100 text-blue-600 rounded-lg"><AlertTriangle className="w-5 h-5" /></div>
        </div>
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wider mb-1">Approved</p>
            <h3 className="text-2xl font-bold text-slate-900">{workOrders.filter(w => w.status === 'APPROVED').length}</h3>
          </div>
          <div className="p-2 bg-emerald-100 text-emerald-600 rounded-lg"><CheckCircle2 className="w-5 h-5" /></div>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
        <div className="p-4 border-b border-slate-200 bg-slate-50 flex gap-4 flex-wrap">
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <input 
              type="text" 
              placeholder="Search work orders, equipment..." 
              className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-orange-500 focus:border-transparent"
            />
          </div>
          <select className="border border-slate-200 rounded-lg text-sm px-3 py-2 bg-white">
            <option>All Statuses</option>
            <option>DRAFT</option>
            <option>EDITED</option>
            <option>APPROVED</option>
            <option>REJECTED</option>
            <option>COMPLETED</option>
          </select>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 uppercase bg-slate-50/80 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 font-semibold">WO Number</th>
                <th className="px-6 py-4 font-semibold">Details</th>
                <th className="px-6 py-4 font-semibold">Equipment</th>
                <th className="px-6 py-4 font-semibold">Priority</th>
                <th className="px-6 py-4 font-semibold">Status</th>
                <th className="px-6 py-4 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {workOrders.map((wo) => (
                <tr key={wo.id} className="hover:bg-slate-50/80 transition-colors group">
                  <td className="px-6 py-4">
                    <Link href={`/work-orders/${wo.id}`} className="font-bold text-slate-900 hover:text-orange-600 font-mono">
                      {wo.woId}
                    </Link>
                    <div className="text-xs text-slate-500 flex items-center mt-0.5">
                      <Clock className="w-3 h-3 mr-1" /> {formatDate(wo.createdAt)}
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="font-semibold text-slate-800 mb-0.5 line-clamp-1">{wo.title}</div>
                    <div className="text-xs text-slate-500 line-clamp-1">Ref: {wo.issue?.title || 'Unknown Issue'}</div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="font-medium text-slate-900">{wo.equipment.equipmentId}</div>
                    <div className="text-xs text-slate-500">{formatEquipmentType(wo.equipment.type)}</div>
                  </td>
                  <td className="px-6 py-4">
                    <span className={cn('px-2.5 py-1 rounded-full text-xs font-semibold uppercase tracking-wide border inline-block', priorityBg(wo.priority))}>
                      {wo.priority}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <span className={cn('px-2.5 py-1 rounded-full text-xs font-medium border inline-block', statusBg(wo.status))}>
                      {formatStatus(wo.status)}
                    </span>
                    {wo.status === 'APPROVED' && wo.approvedBy && (
                      <div className="text-[10px] text-slate-500 mt-1 flex items-center">
                        <CheckCircle2 className="w-3 h-3 mr-0.5 text-emerald-500" /> {wo.approvedBy.name}
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <Link 
                      href={`/work-orders/${wo.id}`}
                      className="inline-flex items-center text-sm font-medium text-orange-600 hover:text-orange-700 transition-colors"
                    >
                      {wo.status === 'DRAFT' || wo.status === 'EDITED' ? 'Review & Approve' : 'View Details'} <ArrowRight className="w-4 h-4 ml-1" />
                    </Link>
                  </td>
                </tr>
              ))}
              {workOrders.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-6 py-12 text-center text-slate-500">
                    No work orders found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
